on:
  push:
    paths:
      - 'Dockerfile.debian'
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.debian
          push: true
          tags: |
            ghcr.io/cornelicorn/toolbox-images/debian:${{ github.sha }}
            ghcr.io/cornelicorn/toolbox-images/debian:actions-${{ github.run_number }}
            ghcr.io/cornelicorn/toolbox-images/debian:latest
